
-- 1 . 

SELECT STUDENT_NAME AS "학생 이름", STUDENT_ADDRESS AS "주소지"
FROM TB_STUDENT
ORDER BY 1;



-- 2 .

SELECT STUDENT_NAME, STUDENT_SSN
FROM TB_STUDENT
WHERE ABSENCE_YN = 'Y'
ORDER BY STUDENT_SSN DESC;



-- 3 . 

SELECT STUDENT_NAME AS "학생이름", STUDENT_NO AS "학번", STUDENT_ADDRESS AS "거주지 주소"
FROM TB_STUDENT

WHERE STUDENT_ADDRESS LIKE '경기%'
AND STUDENT_NO LIKE '9%'
ORDER BY 1;




-- 4 . 

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE DEPARTMENT_NO = '005'
ORDER BY 2;

-- 5 .

SELECT STUDENT_NO, POINT
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
WHERE TERM_NO IN '200402'
AND CLASS_NO = 'C3118100'
ORDER BY POINT DESC;


-- 6. 

SELECT STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);


-- 7 . 

SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO);


-- 8 . 

SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO)
ORDER BY PROFESSOR_NAME;


-- 9 . 
/*
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR
JOIN TB_CLASS_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_CLASS USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문';
*/
SELECT CLASS_NAME, PROFESSOR_NAME
FROM TB_PROFESSOR TP, TB_CLASS_PROFESSOR T, TB_CLASS TS, TB_DEPARTMENT TD
WHERE TP.PROFESSOR_NO = T.PROFESSOR_NO 
AND T.CLASS_NO = TS.CLASS_NO
AND TS.DEPARTMENT_NO = TD.DEPARTMENT_NO 
AND CATEGORY LIKE '인문%'
ORDER BY CLASS_NAME;


-- 10 . 
-- 음악학과 059
SELECT STUDENT_NO AS "학번", STUDENT_NAME AS "학생 이름", ROUND(AVG(POINT),1) AS "전체 평점" 
FROM TB_STUDENT
NATURAL JOIN TB_GRADE
NATURAL JOIN TB_DEPARTMENT
WHERE DEPARTMENT_NO = '059' -- OR DEPARTMENT_NAME = '음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME
ORDER BY 1;



-- 11 . 

SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

-- 11 . 풀이 2

SELECT DEPARTMENT_NAME 학과이름, 
			 STUDENT_NAME 학생이름, 
			 PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT S
JOIN TB_PROFESSOR P ON( COACH_PROFESSOR_NO = PROFESSOR_NO )
JOIN TB_DEPARTMENT D ON(S.DEPARTMENT_NO = D.DEPARTMENT_NO ) 
WHERE STUDENT_NO = 'A313047';

-- 12 . 

SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_STUDENT
JOIN TB_GRADE USING(STUDENT_NO)
JOIN TB_CLASS USING(CLASS_NO) 
WHERE CLASS_NAME = '인간관계론'
AND TERM_NO LIKE '2007%';


-- 13 . 
/*
SELECT CLASS_NAME, PROFESSOR_NO
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO);
WHERE PROFESSOR_NO IS NULL;
*/

SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS
LEFT JOIN TB_CLASS_PROFESSOR USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '예체능'
AND PROFESSOR_NO IS NULL;



-- 14 .

SELECT STUDENT_NAME 학생이름, NVL(PROFESSOR_NAME, '지도교수 미지정') 지도교수
FROM TB_STUDENT ts
LEFT JOIN TB_PROFESSOR tp ON( COACH_PROFESSOR_NO = PROFESSOR_NO )
JOIN TB_DEPARTMENT td ON( ts.DEPARTMENT_NO = td.DEPARTMENT_NO)
WHERE DEPARTMENT_NAME  = '서반아어학과'
ORDER BY STUDENT_NO;





-- 15 . 

SELECT STUDENT_NO 학번, STUDENT_NAME 이름, 
			 DEPARTMENT_NAME "학과 이름", TRUNC(AVG(POINT), 8) 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4.0
ORDER BY 1;


-- 16 .


SELECT CLASS_NO, CLASS_NAME, TRUNC(AVG(POINT), 8)
FROM TB_CLASS
JOIN TB_GRADE USING(CLASS_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE LIKE '전공%'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY CLASS_NO;



-- 240305

SELECT DEPARTMENT_NAME, ROUND(AVG(POINT),1)
FROM TB_DEPARTMENT
JOIN TB_CLASS USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(CLASS_NO)
WHERE CATEGORY = (SELECT CATEGORY
												 FROM TB_DEPARTMENT
											   WHERE DEPARTMENT_NAME = '국어국문학과')	
GROUP BY DEPARTMENT_NAME;





















































