-- 테스트용 테이블 생성!

CREATE TABLE TB_TEST(
	TEST_NO NUMBER PRIMARY KEY,
	TEST_TITLE VARCHAR2(100) NOT NULL,
	TEST_CONTENT VARCHAR2(500) NOT NULL
);

SELECT * FROM TB_TEST;



-- JDBC 240315

SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL ,PHONE, NVL(DEPT_TITLE, '부서없음') DEPT_TITLE, JOB_NAME ,SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON (DEPT_ID = DEPT_CODE) 
JOIN JOB USING(JOB_CODE)
ORDER BY EMP_ID;

SELECT *
FROM EMPLOYEE;


SELECT EMP_ID, EMP_NAME, EMP_NO, EMAIL, PHONE, 
			 NVL(DEPT_TITLE,'부서없음') DEPT_TITLE, JOB_NAME, SALARY
FROM EMPLOYEE
LEFT JOIN DEPARTMENT ON ( DEPT_ID = DEPT_CODE)
JOIN JOB USING(JOB_CODE)
WHERE EMP_ID = ? 
