-- 1. 

SELECT STUDENT_NO 학번, STUDENT_NAME 이름,  TO_CHAR(ENTRANCE_DATE, 'YYYY-MM-DD') 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = '002'
ORDER BY 1 ASC;


-- 2 . 

SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE '___';

-- 3 .
 
SELECT PROFESSOR_NAME 교수이름,
FLOOR( MONTHS_BETWEEN( SYSDATE, TO_DATE('19' || SUBSTR( PROFESSOR_SSN, 1, 6), 'YYMMDD')) /12 ) 나이
FROM TB_PROFESSOR
ORDER BY 2;

-- 4 .

SELECT SUBSTR(PROFESSOR_NAME, 2) 이름
FROM TB_PROFESSOR;

-- 5 . 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) -
			EXTRACT(YEAR FROM TO_DATE('19' || SUBSTR(STUDENT_SSN, 1,6),'YYYYMMDD') ) > 19;

		
-- 6 . 

SELECT TO_CHAR(TO_DATE('2020-12-25'), 'DAY')
FROM DUAL;

-- 7 . 

	SELECT TO_CHAR(TO_DATE('99/10/11', 'YY/MM/DD'),'YYYYMMDD'),-- 2099 / 10 / 11 
				 TO_CHAR(TO_DATE('49/10/11', 'YY/MM/DD'), 'YYYYMMDD'),-- 2049 / 10 / 11
				 TO_CHAR(TO_DATE('99/10/11', 'RR/MM/DD'), 'YYYYMMDD'), --1999 / 10 / 11
				 TO_CHAR(TO_DATE('49/10/11', 'RR/MM/DD'), 'YYYYMMDD') -- 2049 / 10 / 11
	FROM DUAL;	
	
-- 8 . 

SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT
WHERE STUDENT_NO NOT LIKE 'A%';